### ISSUE TITLE
Getting error on sphelper.min.js:1

### ISSUE THREAD

**Issue by manoj247** [jamesdruhan/spHelper#1]
Uncaught ReferenceError: exports is not defined,     at spHelper.min.js:1 

Uncaught TypeError: SP.ClientContext is not a constructor  at e.value (spHelper-stand-alone.min.js:1)

//here is my sample code

function  FnInit(){
		// Initialize spHelper
		var  dataConnection  =  new  spHelper({
		crossDomain  :  false,
		targetSite  :  'https://mytanent.sharepoint.com/sites/SiteColname'
		});
		// Create the callback function that will be executed after the request is completed successfully.

		var  onSuccess  =  function (results){
		console.log('New customer added!');
		}

		// Create the callback function that will be executed if the request fails.
		var  onFailure  =  function (errorMessage){
		console.log('An error has occured!  '  +  errorMessage);
		}
		
		var  itemDetails  = {listName  :  'SSRequests', columnData  :{Title  :{Type  :  'Text',Value  :  'Hello.'}}};
		
		// Perform the spHelper request and send your callback functions.
		dataConnection.addListItem(itemDetails, onSuccess, onFailure);

}

SP.SOD.executeFunc("clienttemplates.js", "clienttemplates", FnInit);

**Comment by jamesdruhan** [comment]
Need a bit more information:

- What version of SharePoint?
- How are you implementing spHelper? .. Add-in? Master Page? Script Editor? Context Editor?
- Did you load the SharePoint includes before spHelper?

Paste your full code with the above answers and I'll do my best to help.

**Comment by manoj247** [comment]
Hi James
Thank for you your reply.
What version of SharePoint?  i used Sharepoint online team site.
How are you implementing spHelper? .. Add-in? Master Page? Script Editor? Context Editor?
Add in, i add javascript references in a site page. (i used webpart page)

here is the references i added in the site page.

<asp:Content ContentPlaceHolderId="PlaceHolderMain" runat="server">
<script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/SiteAssets/JS/spHelper.min.js" ></script>
<script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/_layouts/15/MicrosoftAjax.js" ></script>
<script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/_layouts/15/SP.Runtime.js" ></script>
<script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/_layouts/15/SP.UserProfiles.js" ></script>

<script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/SiteAssets/JS/spHelper-stand-alone.min.js" ></script>
<script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/SiteAssets/JS/dashboard-sphelper.js" ></script>

</asp:Content>

Did you load the SharePoint includes before spHelper? 
Not sure - as you mentioned in your sample code.  see the answer to the 2nd question.

Paste your full code with the above answers and I'll do my best to help.
i have two pages.  
1)a aspx page created in sitepages library .  
2) a javascript file called  "dashboard-sphelper.js" which is uploaded to sitesassets/JS location.
in the javascript file,  i have the following script to add a list item to the splist  called "SSrequests".
my understanding is to call this FnInit() function in the page_load. 
Please help me here.. thanks in advance.
//***************my js code starts here in dashboard-sphelper.js**********************
function  FnInit(){
		// Initialize spHelper
		var  dataConnection  =  new  spHelper({
		crossDomain  :  false,
		targetSite  :  'https://mytenant.sharepoint.com/sites/sysService'
		});
		// Create the callback function that will be executed after the request is completed successfully.

		var  onSuccess  =  function (results){
		alert('New customer added!');
		}

		// Create the callback function that will be executed if the request fails.
		var  onFailure  =  function (errorMessage){
		alert('An error has occured!  '  +  errorMessage);
		}
		
		var  itemDetails  = {listName  :  'SSRequests', columnData  :{Title  :{Type  :  'Text',Value  :  'Hello.'}}};
		
		// Perform the spHelper request and send your callback functions.
		dataConnection.addListItem(itemDetails, onSuccess, onFailure);

}

SP.SOD.executeFunc("clienttemplates.js", "clienttemplates", FnInit);

**Comment by jamesdruhan** [comment]
Thank you for the followup information. The order of your loaded scripts is very important. You must load the SharePoint required scripts before spHelper. You are also loading spHelper twice. The order of your loads should look more like this:

```html
<asp:Content ContentPlaceHolderId="PlaceHolderMain" runat="server">
  <script  type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/_layouts/15/MicrosoftAjax.js"></script>
  <script  type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/_layouts/15/SP.Runtime.js"></script>
  <script  type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/_layouts/15/SP.UserProfiles.js"></script>
  <script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/SiteAssets/JS/spHelper-stand-alone-min.js"></script>
  <script type="text/javascript" src="https://mytanent.sharepoint.com/sites/sysService/SiteAssets/JS/dashboard-sphelper.js" ></script>
</asp:Content>
```

The Microsoft files (MicrosoftAjax/Runntime/UserProfile) are actually loaded by default via the master page. However this forces them to be loaded before spHelper. If they are loaded after, you will receive errors.

Your **dashboard-sphelper.js** should look something like this:

```javascript
function FnInit()
{
	// Initialize spHelper
	var dataConnection = new spHelper({
		crossDomain : false,
		targetSite : 'https://mytenant.sharepoint.com/sites/sysService'
	)};

	var  onSuccess  =  function (results){
	alert('New customer added!');
	}

	// Create the callback function that will be executed if the request fails.
	var  onFailure  =  function (errorMessage){
	alert('An error has occured!  '  +  errorMessage);
	}
	
	var  itemDetails  = {listName  :  'SSRequests', columnData  :{Title  :{Type  :  'Text',Value  :  'Hello.'}}};
	
	// Perform the spHelper request and send your callback functions.
	dataConnection.addListItem(itemDetails, onSuccess, onFailure);
});

SP.SOD.executeFunc("clienttemplates.js", "SPClientTemplates", FnInit);
```
Your FnInit function should contain ALL your application / request logic.
